In [129]:
import pandas as pd

In [152]:
df = pd.read_csv('vacancies_merged_prizn (2) (1).csv', sep=',')
df

,Unnamed: 0,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,...,company_description,vacancy_count,staff_count,catalogues,source,dms,ai,work_format,education,1с
0,0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,...,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
1,1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,...,NaN,NaN,NaN,NaN,scrapping,1,0,0,0,0
2,2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,...,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
3,3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,...,NaN,NaN,NaN,NaN,scrapping,1,0,0,2,0
4,4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,...,NaN,NaN,NaN,NaN,scrapping,0,0,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,"Российская государственная корпорация, объедин...",3.0,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0,0,0
30863,30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,"Наша Школа - это пространство возможностей, тв...",1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0
30864,30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,Ведущий российский бренд безалкогольных напитк...,0.0,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1,0,0
30865,30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,Lasertech — один из ведущих игроков на рынке п...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,1,1
30866,30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...",...,Производство специальных жидкостей для автомоб...,1.0,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,1

In [153]:
import numpy as np

In [154]:
#переиспользуем код коллег
df['payment_from_clean'] = df['payment_from']
df['payment_to_clean'] = df['payment_to']

# если payment_to меньше 1000 & payment_from > 1000, то payment_to * 1000
mask = (df['payment_to'] < 1000) & (df['payment_from'] > 1000)
df.loc[mask, 'payment_to_clean'] = df.loc[mask, 'payment_to'] * 1000

# если оба < 1000, то payment_from * 1000 + payment_to & payment_to = null
mask = (df['payment_from'] < 1000) & (df['payment_to'] < 1000)
df.loc[mask, 'payment_from_clean'] = df.loc[mask, 'payment_from'] * 1000
df.loc[mask, 'payment_to_clean'] = np.nan

# 0 = null
df.loc[df['payment_from_clean'] < 10, 'payment_from_clean'] = np.nan
df.loc[df['payment_to_clean'] < 10, 'payment_to_clean'] = np.nan

In [155]:
df

,Unnamed: 0,profession,profession_full,vacancy_description,date_published,payment_from,payment_to,experience,employment,city,...,staff_count,catalogues,source,dms,ai,work_format,education,1с,payment_from_clean,payment_to_clean
0,0,Начальник отдела,Руководитель отдела сопровождения внутренней и...,"Компания ""Санкт-Петербургская биржа"" Вам предс...",2026-03-25,NaN,NaN,NaN,Полная занятость,Москва,...,NaN,NaN,scrapping,1,0,0,0,0,NaN,NaN
1,1,Java,Java (Senior)( ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМ...,"Компания ""ТЕХНОЛОГИИ ОТРАСЛЕВОЙ ТРАНСФОРМАЦИИ""...",2026-03-27,NaN,NaN,Более 6 лет,Полная занятость,Москва,...,NaN,NaN,scrapping,1,0,0,0,0,NaN,NaN
2,2,Специалист,Middle+ AQA специалист,"Компания ""Компания Ритейл Сервис"" Мы - аккреди...",2026-03-26,140000.0,180000.0,NaN,Полная занятость,Барнаул,...,NaN,NaN,scrapping,0,0,2,0,0,140000.0,180000.0
3,3,Технолог,Технолог( АКРИХИН ),"Компания ""АКРИХИН"" Обязанности: Обеспечивать ...",2026-03-25,NaN,NaN,NaN,Полная занятость,Старая Купавна,...,NaN,NaN,scrapping,1,0,0,2,0,NaN,NaN
4,4,Project manager,Project Manager Game Dev( Beresnev Games ),"Компания ""Beresnev Games"" Мы в поиске Project ...",2026-03-26,NaN,NaN,NaN,Полная занятость,Москва,...,NaN,NaN,scrapping,0,0,2,0,0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30862,30862,Практикант / стажёр Документовед,Практикант / стажёр Документовед,ГНЦ РФ АО «ВНИИНМ» разрабатывает конструкционн...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,менее 50,"[{'id': 1, 'title': 'Административная работа, ...",api,1,0,0,0,0,NaN,NaN
30863,30863,Технический специалист/ Системный администратор,Технический специалист/ Системный администратор,"Обязанности:\n• Установка, обновление и админи...",2026-04-08,80000.0,100000.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,0,80000.0,100000.0
30864,30864,Стажер в IT отдел,Стажер в IT отдел,Здесь занимаются поддержкой IT-платформ и их р...,2026-04-08,0.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,более 5000,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,1,0,1,0,0,NaN,NaN
30865,30865,Сотрудник технической поддержки,Сотрудник технической поддержки,"Добрый день!\nМы компания Lasertech, занимаемс...",2026-04-07,80000.0,0.0,NaN,NaN,"{'id': 4, 'title': 'Москва', 'declension': 'в ...",...,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,1,1,80000.0,NaN
30866,30866,Специалист по маркировке в системе Честный зна...,Специалист по маркировке в системе Честный зна...,"Обязанности:\n• \n• Работа в системах: 1С, Чес...",2026-04-07,80000.0,110000.0,NaN,NaN,"{'id': 1396, 'title': 'Мытищи', 'declension': ...",...,менее 50,"[{'id': 33, 'title': 'IT, Интернет, связь, тел...",api,0,0,0,0,1,80000.0,110000.0

In [156]:
df[df['ai'] == 1]['profession']

12                                                Менеджер
23                                        Senior developer
45                                                     Cio
50                                         Сетевой инженер
59                                       Менеджер проектов
                               ...
29399    Стажёр Data Science в департамент валидации и ...
29865        Начинающий инженер-исследователь в области ИИ
29867    Директор по педагогическому дизайну (языковые ...
29868                            Штатный дизайнер продукта
30812    Заместитель руководителя службы охраны труда (...
Name: profession, Length: 2209, dtype: object

In [157]:
df['payment_avg'] = np.where(
    (df['payment_from_clean'] > 0) & (df['payment_to_clean'] > 0),
    (df['payment_from_clean'] + df['payment_to_clean']) / 2,
    np.nan
)

# Гипотеза 1

H0: у вакансий связанных с ИИ зарплаты не отличаются от зарплат вакансий не связанных с ИИ

H1: у вакансий связанных с ИИ зарплаты отличаются от зарплат вакансий не связанных с ИИ

И в какую сторону и на сколько процентов они отличаются нам тоже интересно

In [158]:
from scipy import stats

In [159]:
df_temp = df.dropna(subset=['payment_avg'])

In [160]:
a = df_temp['payment_avg'][df_temp['ai'] == 1]
b = df_temp['payment_avg'][df_temp['ai'] == 0]

In [161]:
a.shape

(231,)

In [162]:
b.shape

(6374,)

Значений у нас везде > 30, по ЦПТ распределение выборочных средних сойдется к нормальному, поэтому ттест справится. Поставим доп параметр equal_var=False, чтобы не проверять неоднородность гипотез и перестраховаться

In [163]:
import plotly.express as px

In [164]:
fig = px.histogram(
    df,
    x='payment_avg',
    color='ai',
    marginal='box',
    barmode='overlay'
)

fig.show()

In [165]:
stats.ttest_ind(a, b, equal_var=False)

TtestResult(statistic=np.float64(8.350239940284167), pvalue=np.float64(5.844415394869378e-15), df=np.float64(235.65076268305833))

In [166]:
uplift = round(((a.mean()/b.mean()) - 1) * 100, 1)
print(f'{uplift}%')

62.4%

pvalue < 0,05 => отклоним H0, то есть есть основания полагать, что на уровне значимости 5% пользователи в группах а и б ведут себя статзначимо различно.

То есть да, вакансии в которых есть требования к владению ИИ предлагают большую зарплату, причем большую на 62%

# Гипотеза 2

график зп по времени - статзначимый ли рост и есть ли он вообще и причем тут инфляция

In [167]:
df['date_published'] = pd.to_datetime(df['date_published'])
df['month'] = df['date_published'].dt.to_period('M').astype(str)
df['day'] = df['date_published'].dt.to_period('D').astype(str)
df_trend = df.groupby('day')['payment_avg'].agg(['mean']).dropna().reset_index()
df_trend

           day           mean
0   2026-03-02  120000.000000
1   2026-03-03  140000.000000
2   2026-03-22  178333.333333
3   2026-03-23  137500.000000
4   2026-03-25  134635.430039
5   2026-03-26  129259.897829
6   2026-03-27  127453.681710
7   2026-03-28  136113.379346
8   2026-03-30  102799.300000
9   2026-03-31   71048.000000
10  2026-04-01  106666.666667
11  2026-04-02   79353.448276
12  2026-04-03   92325.764249
13  2026-04-04   82598.900000
14  2026-04-05   86326.086957
15  2026-04-06  100161.779412
16  2026-04-07   86493.438679
17  2026-04-08   81217.148649
18  2026-04-09   70451.123885
19  2026-04-10   68738.172352

In [168]:
fig = px.line(
    df_trend,
    x='day',
    y='mean',
    markers=True
)

fig.show()

Данных мало, не будем делать выводы

# Гипотеза 3
Линейная регрессия - можно ли предсказать зп по признакам - город, профессия, work format, education, dms

Что хочется узнать - насколько хорошо признаки объсняют зп (корреляция)

In [169]:
#переиспользуем код коллег
import ast # https://habr.com/ru/companies/piter/articles/493424/

def extract_city_name(city_value):
    if pd.isna(city_value):
        return np.nan
    if str(city_value).startswith('{'):
          city_dict = ast.literal_eval(city_value)
          return city_dict.get('title', np.nan)
    else:
          return city_value

df['city_name'] = df['city'].apply(extract_city_name)

In [170]:
#переиспользуем код коллег
city_counts = df['city_name'].value_counts()

min_count = 200
top_cities = city_counts[city_counts >= min_count].index.tolist() #убираем те, которые встречаются меньше 200 раз

df['city_grouped'] = df['city_name'].apply(
    lambda x: x if x in top_cities else 'Другие'
)

df['city_grouped'].nunique()

20

In [171]:
df = pd.get_dummies(df, columns=['city_grouped'], drop_first=True)

In [172]:
city_cols = [i for i in df.columns if i.startswith('city_grouped_')]

In [173]:
c = ['profession', 'work_format', 'education', 'dms', 'payment_avg', 'ai']
df_clean = df[c + city_cols].dropna(subset=c)

top_15 = df_clean['profession'].value_counts().nlargest(15).index
df_clean['profession_grouped'] = df_clean['profession'].apply(
    lambda x: x if x in top_15 else 'Другие')

Построим линейную регрессию методом OLS (метод наименьших квадратов), чтобы вместо ручного подсчете R2, pvalue и коэффициентов линейной регресии, можно было автоматически получить влияние (коэффициенты) каждого признака
(профессии, города, образования) на целевую переменную - зарплату, и еще и проверку их статзначимости.

In [177]:
import statsmodels.api as sm

X = pd.get_dummies(df_clean[['profession_grouped', 'work_format']], drop_first=True)

X = pd.concat([X, df_clean[city_cols[1:]]], axis=1)

X['education'] = df_clean['education']
X['dms'] = df_clean['dms']
X['ai'] = df_clean['ai']

y = df_clean['payment_avg']

X = sm.add_constant(X).astype(float)
model = sm.OLS(y, X).fit()

print(model.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:            payment_avg   R-squared:                       0.277
Model:                            OLS   Adj. R-squared:                  0.273
Method:                 Least Squares   F-statistic:                     68.06
Date:                Fri, 10 Apr 2026   Prob (F-statistic):               0.00
Time:                        22:46:39   Log-Likelihood:                -82058.
No. Observations:                6605   AIC:                         1.642e+05
Df Residuals:                    6567   BIC:                         1.644e+05
Df Model:                          37
Covariance Type:            nonrobust
================================================================================================================================
                                                                   coef    std err          t      P>|t|      [0.025      0.975]
--------------------------------------------------------------------------------------------------------------------------------
const                                                         3.104e+04   5875.599      5.283      0.000    1.95e+04    4.26e+04
work_format                                                   1.302e+04   1191.368     10.925      0.000    1.07e+04    1.54e+04
profession_grouped_Другие                                     4.318e+04   5871.430      7.354      0.000    3.17e+04    5.47e+04
profession_grouped_Инженер                                    7.033e+04   6812.547     10.323      0.000     5.7e+04    8.37e+04
profession_grouped_Инженер технолог                           4.136e+04   7426.161      5.569      0.000    2.68e+04    5.59e+04
profession_grouped_Информационные технологии / IT / Интернет  7.589e+04   7817.970      9.708      0.000    6.06e+04    9.12e+04
profession_grouped_Менеджер                                   7.784e+04   8747.027      8.899      0.000    6.07e+04     9.5e+04
profession_grouped_Начальник отделения почтовой связи         7009.2041   8268.807      0.848      0.397   -9200.347    2.32e+04
profession_grouped_Оператор по работе с клиентами             6027.8936   8997.191      0.670      0.503   -1.16e+04    2.37e+04
profession_grouped_Программист                                9.315e+04   8489.577     10.973      0.000    7.65e+04     1.1e+05
profession_grouped_Программист 1с                             1.143e+05   8487.353     13.470      0.000    9.77e+04    1.31e+05
profession_grouped_Разработчик                                9.747e+04   7537.539     12.932      0.000    8.27e+04    1.12e+05
profession_grouped_Руководитель проектов                      1.031e+05   8561.319     12.039      0.000    8.63e+04     1.2e+05
profession_grouped_Сервисный инженер                          6.599e+04   7906.597      8.347      0.000    5.05e+04    8.15e+04
profession_grouped_Системный администратор                    3.503e+04   7187.802      4.874      0.000    2.09e+04    4.91e+04
profession_grouped_Специалист                                 4.142e+04   7531.529      5.500      0.000    2.67e+04    5.62e+04
profession_grouped_Технолог                                   6.594e+04   8455.430      7.798      0.000    4.94e+04    8.25e+04
city_grouped_Екатеринбург                                     1.239e+04   4988.788      2.484      0.013    2611.358    2.22e+04
city_grouped_Ижевск                                          -6664.0195   9756.104     -0.683      0.495   -2.58e+04    1.25e+04
city_grouped_Казань                                               1e+04   5630.176      1.776      0.076   -1036.719     2.1e+04
city_grouped_Краснодар                                        1.142e+04   6103.819      1.872      0.061    -541.451    2.34e+04
city_grouped_Красноярск                                       2.333e+04   7108.237      3.282      0.001    9391.414    3.73e+04
city_grouped_Москва                                           5.894e+04   2014.322     29.259      0.000     5.5e+04    6.29e+04
city_grouped_Нижний Новгород                                  5458.9090   5894.488      0.926      0.354   -6096.205     1.7e+04
city_grouped_Новосибирск                                      2.959e+04   6033.498      4.904      0.000    1.78e+04    4.14e+04
city_grouped_Омск                                            -1339.9774   1.03e+04     -0.130      0.896   -2.15e+04    1.88e+04
city_grouped_Пермь                                           -3340.9508   9176.858     -0.364      0.716   -2.13e+04    1.46e+04
city_grouped_Ростов-на-Дону                                    861.4373   7580.805      0.114      0.910    -1.4e+04    1.57e+04
city_grouped_Самара                                          -1.331e+04   6133.386     -2.171      0.030   -2.53e+04   -1290.197
city_grouped_Санкт-Петербург                                  1.924e+04   2543.209      7.565      0.000    1.43e+04    2.42e+04
city_grouped_Тула                                              280.8290   7297.036      0.038      0.969    -1.4e+04    1.46e+04
city_grouped_Тюмень                                           8346.6538   8979.172      0.930      0.353   -9255.444    2.59e+04
city_grouped_Уфа                                              3.349e+04   7753.107      4.320      0.000    1.83e+04    4.87e+04
city_grouped_Хабаровск                                        3088.7276   6496.268      0.475      0.634   -9646.071    1.58e+04
city_grouped_Челябинск                                       -4520.5091   8458.407     -0.534      0.593   -2.11e+04    1.21e+04
education                                                     7755.6431    940.984      8.242      0.000    5911.009    9600.277
dms                                                           4273.5223   1664.204      2.568      0.010    1011.142    7535.903
ai                                                            3.474e+04   4257.521      8.160      0.000    2.64e+04    4.31e+04
==============================================================================
Omnibus:                     3244.194   Durbin-Watson:                   1.724
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            28536.145
Skew:                           2.170   Prob(JB):                         0.00
Kurtosis:                      12.212   Cond. No.                         47.5
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

Выводы:  
1) R2 = 0.28
наши признаки (город, профессия, ии, наличие дмс, уровень образования) объясняют 28% разброса зарплат -> то есть все таки есть какая-то статзначимая свзяь между зп и признаками, hr не ставят зп на рандом
2) У Москвы самый большой статзначимый вес из городов - то есть действительно в Москве выше зп
3) Из профессий самая большая связь у разработчика

Еще раз подтвердили статзначимое влияние ии, образования и дмс на зп